### ISSUE TITLE
ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by SeekPoint** [lvjianxin/Knowledge-extraction#1]
ub16c9@ub16c9-gpu:~/ub16_prj/Knowledge-extraction$ python3 main.py 
vocab_size: 3905
Namespace(CRF=True, batch_size=64, clip=5.0, demo_model='1521112368', dropout=0.5, embedding_dim=300, epoch=40, hidden_dim=300, lr=0.001, mode='demo', optimizer='Adam', pretrain_embedding='random', shuffle=True, test_data='data_path', train_data='data_path', update_embedding=True)
None
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
============= demo =============
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    saver.restore(sess, ckpt_file)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1534, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by SeekPoint** [comment]
figured it out

**Comment by lvjianxin** [comment]
build a new floder "save_path"
